### ISSUE TITLE
Ask Save when already saved

### ISSUE THREAD

**Issue by x27** [x27/CFT#14]

**Comment by x27** [comment]
I can't repeat the error
But it was

**Comment by noamlivne** [comment]
In the latest CFT 0.9 for example, do some change in your alice.cft file, press CTRL+S to save.
It is saved successfully.
Press the X to exit the program and you will be prompted to "save the changes that were found" (even though there were no changes).
No need for that, if there were no changes.

**Comment by x27** [comment]
Changed the way of checking changes in a file. Fixed in 2.0.0.5
