### ISSUE TITLE
Add option to import multiple frequencies from .csv files such as DSDPlus and DSD FME

### ISSUE THREAD

**Issue by noamlivne** [x27/CFT#24]
Add option to import A LOT of frequencies from .csv files such as DSDPlus and DSD FME.
Useful when we already have the lists prepared and we only need to (manually) create and save them again in CFT with their key(s).
Creating + Saving for each key for tens of frequencies can be tedious.
Plus if there will be an option to give each of those frequencies the (same) key(s) - that would be great.

**Comment by x27** [comment]
Added in v2.0.0.12
