### ISSUE TITLE
DES-OFB decryption with KEYID or Networkid only

### ISSUE THREAD

**Issue by mrscanner2008** [x27/CFT#36]
I have a 200 site P25 system with an average of 5 to 10 frequencies per site, is there a way to listen to DES-OFB without having to enter the 200 sites and frequencies? Maybe decoding with only the KEYID or with the Network ID!! 
 
On this system there are 2 departments that I would like to listen to with each their DES-OFB and KEYID key, so I would like to avoid entering the 200 sites and frequencies twice for these 2 departments

**Comment by x27** [comment]
Adden in CFT v2.0.0.30
