### ISSUE TITLE
Rssi reading not correct?

### ISSUE THREAD

**Issue by Wonkaski** [x27/CFT#46]
I am using the latest .36 version for my 436HP and it seems that the rssi readings are not quite working, no matter the signal is strong or weak, it is always between -100 and -115, and even with my radio transmitting right next to the scanner, it still shows around -105, which is not normal.
Don't know if it is just my scanner problem, or Uniden just did not provide the information from their hardware and therefore the value is just a estimate.

**Comment by x27** [comment]
I've seen nothing but unsubstantiated assertions. 
neither what data you believe to be false, nor what data uniden believes to be true, nor the results of forum searches. what should I do with this issue?
I took the voltage that uniden provides and converted it to dbm, I found the values to be comparable to those of the SDS100 scanner, I added it to the release.

**Comment by Wonkaski** [comment]
I am not trying to make unsubstantiated assertions here, NOT even a assertion.
I am just reporting what I see as an issue from my scanner with the firmware, is there any reason I should lie on this and make negative comments about the firmware? I could have just flashed back to official.
And I said it could be just my scanner's issue, but I am just saying it here to see if anyone else having the same issue.
I don't know much about technology, **Just trying to make the firmware better**, Why the hostility here??
I will post a video or something later.

**Comment by Wonkaski** [comment]
![IMG_1847](https://github.com/user-attachments/assets/f40a12c6-207d-41c7-8d60-bbcf6b5bc620)

**Comment by Wonkaski** [comment]
The lowest reading I can get on my 436HP is -100dBm, which is not normal. The transmitting radio (Hytera with red LED) is right next to it, and my Motorola reading is -9.99dBm. So I am just curious here, is this just me facing this issue? A bad BCD436HP?

**Comment by x27** [comment]
https://t.me/openscannerchat/6155

**Comment by x27** [comment]
Fixed in FW v1.99.39
